#!/bin/bash


ls media/ > media_list

total_words=$(wc -w < media_list)
base_url=https://raw.githubusercontent.com/thegrims/arduino-distance-sensor-code/master/media/

echo $total_words
read -r -a media_array <<< $(cat media_list)

for ((i=0; i<$((total_words-1)); i++))
do
  echo -e ![alt text]'('$base_url${media_array[i]}')\n' >> README.md
done
